<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-01T12:19:34 IST" name="Suite" finished-at="2025-06-01T12:19:55 IST" duration-ms="20937">
    <groups>
    </groups>
    <test started-at="2025-06-01T12:19:34 IST" name="Test_12" finished-at="2025-06-01T12:19:55 IST" duration-ms="20937">
      <class name="test.Test4">
        <test-method is-config="true" signature="setUp()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:34 IST" name="setUp" finished-at="2025-06-01T12:19:39 IST" duration-ms="4737" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="preTest()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:39 IST" name="preTest" finished-at="2025-06-01T12:19:39 IST" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preTest -->
        <test-method signature="testFor400068()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:39 IST" name="testFor400068" finished-at="2025-06-01T12:19:48 IST" duration-ms="8789" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor400068 -->
        <test-method signature="testFor400069()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:48 IST" name="testFor400069" finished-at="2025-06-01T12:19:51 IST" duration-ms="2829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor400069 -->
        <test-method signature="testFor400070()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:51 IST" name="testFor400070" finished-at="2025-06-01T12:19:54 IST" duration-ms="3177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor400070 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.Test4@2a693f59]" started-at="2025-06-01T12:19:55 IST" name="tearDown" finished-at="2025-06-01T12:19:55 IST" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.Test4 -->
      <class name="test.Test3">
        <test-method is-config="true" signature="preTest()[pri:0, instance:test.Test3@52f27fbd]" started-at="2025-06-01T12:19:54 IST" name="preTest" finished-at="2025-06-01T12:19:54 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preTest -->
        <test-method signature="Test3()[pri:0, instance:test.Test3@52f27fbd]" started-at="2025-06-01T12:19:54 IST" name="Test3" finished-at="2025-06-01T12:19:55 IST" duration-ms="786" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The title does not match expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The title does not match expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at test.Test3.Test3(Test3.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
      </class> <!-- test.Test3 -->
    </test> <!-- Test_12 -->
  </suite> <!-- Suite -->
</testng-results>
